
name: Compilar APK Automático

on:
  push:
    branches:
      - main # O la rama que uses por defecto (puede ser master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Dar permisos a Gradle
        run: chmod +x ./gradlew

      - name: Compilar APK de la App
        run: ./gradlew assembleDebug

      - name: Subir APK listo para descargar
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
